=======================
test 7-base_geometry.py
=======================

>>> BaseGeometry = __import__('7-base_geometry').BaseGeometry

test cases:
-----------

>>> bg = BaseGeometry()

>>> bg.integer_validator("positive", 3)

>>> bg.integer_validator("negative", -3)
Traceback (most recent call last):
ValueError: negative must be greater than 0

>>> bg.integer_validator("char", 'a')
Traceback (most recent call last):
TypeError: char must be an integer

>>> bg.integer_validator("inf", float('inf'))
Traceback (most recent call last):
TypeError: inf must be an integer

>>> bg.integer_validator("none", None)
Traceback (most recent call last):
TypeError: none must be an integer

>>> bg.integer_validator("none2", )
Traceback (most recent call last):
TypeError: integer_validator() missing 1 required positional argument: 'value'

>>> bg.integer_validator(, 12)
Traceback (most recent call last):
SyntaxError: invalid syntax

>>> bg.integer_validator()
Traceback (most recent call last):
TypeError: integer_validator() missing 2 required positional arguments: 'name' and 'value'

>>> bg.integer_validator(12, 12)

>>> bg.integer_validator("nan", float('Nan'))
Traceback (most recent call last):
TypeError: nan must be an integer

>>> bg.integer_validator("str", "dog")
Traceback (most recent call last):
TypeError: str must be an integer

>>> bg.integer_validator("tripple", 12, 13)
Traceback (most recent call last):
TypeError: integer_validator() takes 3 positional arguments but 4 were given

>>> bg.area()
Traceback (most recent call last):
Exception: area() is not implemented

>>> bg.integer_validator("float", 1.2)
Traceback (most recent call last):
TypeError: float must be an integer

>>> bg.integer_validator("tuple", (1, 2))
Traceback (most recent call last):
TypeError: tuple must be an integer

>>> bg.integer_validator("list", [1, 2])
Traceback (most recent call last):
TypeError: list must be an integer

>>> bg.integer_validator("array", {1, 2})
Traceback (most recent call last):
TypeError: array must be an integer

>>> bg.integer_validator("alone")
Traceback (most recent call last):
TypeError: integer_validator() missing 1 required positional argument: 'value'

>>> bg.integer_validator(12)
Traceback (most recent call last):
TypeError: integer_validator() missing 1 required positional argument: 'value'

>>> bg.integer_validator("zero", 0)
Traceback (most recent call last):
ValueError: zero must be greater than 0
